spring:
 data:
   mongodb:
#     authentication-database:
     username: ${MONGO_USER}
     password: ${MONGO_PASSWORD}
     database: ${MONGO_DATABASE}
     port: ${MONGO_PORT}
     host: ${MONGO_HOST}
server:
 port: 8082